@startuml
  (*) --> ===B1===
  --> "Start"
   --> ===MAX===
  --> " "
  --> "parallel Activity 4"

  ===B1=== --> "End"
     --> ===MAX===
   ===B3=== --> "用户A"
   ===B3=== --> "用户B"
   ===B3=== --> "用户C"
===B1=== --> "Hight"
   --> ===MAX===
===B1=== --> "Low"
   --> ===MIN===
--> ===B1===
  --> "Start"
   --> ===MIN===
   --> ===B1===
     --> "End"
      --> ===MIN===
  --> (*)

@enduml